#!/bin/bash -x

#while-menu2: a menu driven system information program

DELAY=3 #number of seconds to display results

while true; do
    #clear
    echo "
        Please Select:

        A. Display System Information
        B. Display Disk Space
        C. Display Home Space Utilization
        Q. Quit
    "
    read -p "Please selection [A, B, C or Q] > "
    echo "REPLY: $REPLY"


    case $REPLY in
        #*.txt) echo "This is a test"
               #;;
        q|Q) echo "Program terminated."
             exit
             ;;
        a|A) echo "Hostname: $HOSTNAME"
             uptime
             ;;
        b|B) df -h
             ;;
        c|C) if [[ $(id -u) -eq 0 ]]; then
                 echo "Home Space Utilization (All Users)"
                 du -sh /home/*
             else
                 echo "Home Space Utilization ($USER)"
                 du -sh $HOME
             fi
             ;;
        *)   echo "Invalid entry" >&2
             exit 1
             ;;
    esac

    #if [[ $REPLY =~ ^[0-3]$ ]]; then
        #if [[ $REPLY == 1 ]]; then
            #echo "Hostname: $HOSTNAME"
            #uptime
            #sleep $DELAY
            #continue
        #fi
        #if [[ $REPLY == 2 ]]; then
            #df -h
            #sleep $DELAY
            #continue
        #fi
        #if [[ $REPLY == 3 ]]; then
            #if [[ $(id -u) -eq 0 ]]; then
                #echo "Home Space Utilization (All User)"
                #du -sh /home/*
            #else
                #echo "Home Space Utilization ($USER)"
                #du -sh $HOME
            #fi
            #sleep $DELAY
            #continue
        #fi
        #if [[ $REPLY == 0 ]]; then
            #break
        #fi
    #else
        #echo "Invalid entry."
        #sleep $DELAY
    #fi
done
echo "Program terminated."
